export const Locals = {
    SALE: "FOR SALE",
    BOUGTH: "LAND BOUGHT",
    TRADE_ERROR: "YOU AND YOUR OPPONENT DO NOT HAVE PROPERTY TO BUY OR SELL",
    BUILD_ERROR: "BUY ALL PROPERTY OF ANY GROUP TO BUY"
}